version: "3.7"

services:
  constant:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /constant
    volumes:
      - ./:/constant

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=constant
      - MONGO_INITDB_ROOT_USERNAME=amar
      - MONGO_INITDB_ROOT_PASSWORD=pdnejoh
    volumes:
      - todo-mongo-data:/data/db
    ports:
      - "27017:27017"
volumes:
  todo-mongo-data:
